export const MOCK_LISTINGS = [
  {
    id: '1',
    title: 'iPhone 15 Pro - Titanium Gray',
    description: 'Perfect condition, like new. 256GB storage.',
    price: 999.0,
    currency: 'EUR',
    status: 'active',
    category_id: 'electronics',
    user_id: 'user-1',
    images: ['https://images.unsplash.com/photo-1696446701796-da61225697cc'],
    location: 'Bratislava',
    created_at: new Date().toISOString(),
    is_featured: true,
  },
  {
    id: '2',
    title: 'BMW X5 2023',
    description: 'Black sapphire, M Sport package, fully loaded.',
    price: 75000.0,
    currency: 'EUR',
    status: 'active',
    category_id: 'vehicles',
    user_id: 'user-2',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e'],
    location: 'Kosice',
    created_at: new Date().toISOString(),
    is_featured: false,
  },
  {
    id: '3',
    title: 'Modern Apartment in Old Town',
    description: '2 rooms, 65m2, fully furnished, quiet street.',
    price: 1200.0,
    currency: 'EUR',
    status: 'active',
    category_id: 'real-estate',
    user_id: 'user-3',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'],
    location: 'Bratislava',
    created_at: new Date().toISOString(),
    is_featured: true,
  },
]
