import type { Meta, StoryObj } from '@storybook/react-vite';
import { Breadcrumbs } from '@/components/ui/breadcrumbs';

const meta: Meta<typeof Breadcrumbs> = {
    title: 'UI/Breadcrumbs',
    component: Breadcrumbs,
    tags: ['autodocs'],
    parameters: {
        nextjs: {
            appDirectory: true,
            navigation: {
                pathname: '/en/admin/settings',
            },
        },
    },
};

export default meta;
type Story = StoryObj<typeof Breadcrumbs>;

export const Default: Story = {
    args: {
        items: [
            { label: 'Admin', href: '/admin' },
            { label: 'Users', href: '/admin/users' },
            { label: 'Edit Profile' },
        ],
    },
};

export const AutoGenerated: Story = {
    args: {},
};
